// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-nMddOG2OEjaMBQD6uzwBohpEw8CSy4',
    appId: '1:826115519116:web:f15100b40f3841e75ec1a9',
    messagingSenderId: '826115519116',
    projectId: 'eapp-2f7ee',
    authDomain: 'eapp-2f7ee.firebaseapp.com',
    storageBucket: 'eapp-2f7ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAse056oWsEowOzSYXc57-ZC5tIf4FrDwk',
    appId: '1:826115519116:android:80675534b2a395515ec1a9',
    messagingSenderId: '826115519116',
    projectId: 'eapp-2f7ee',
    storageBucket: 'eapp-2f7ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9HxdLn1JUPXJG5GSGLRQrLPWXBky5yI',
    appId: '1:826115519116:ios:1a8d2ca19cf05faa5ec1a9',
    messagingSenderId: '826115519116',
    projectId: 'eapp-2f7ee',
    storageBucket: 'eapp-2f7ee.appspot.com',
    iosBundleId: 'com.example.eapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9HxdLn1JUPXJG5GSGLRQrLPWXBky5yI',
    appId: '1:826115519116:ios:1a8d2ca19cf05faa5ec1a9',
    messagingSenderId: '826115519116',
    projectId: 'eapp-2f7ee',
    storageBucket: 'eapp-2f7ee.appspot.com',
    iosBundleId: 'com.example.eapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu-nMddOG2OEjaMBQD6uzwBohpEw8CSy4',
    appId: '1:826115519116:web:ba2b2f7e7122d47e5ec1a9',
    messagingSenderId: '826115519116',
    projectId: 'eapp-2f7ee',
    authDomain: 'eapp-2f7ee.firebaseapp.com',
    storageBucket: 'eapp-2f7ee.appspot.com',
  );

}